on:
  push:
    tags:
    - 'v*'

name: Build Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build project
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - uses: actions/cache@v1
        env:
          node-version: 12
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}
      - name: Get Current Tag
        id: get_current_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Get Previous tag
        id: previous_tag
        run: echo ::set-output name=tag::$(git tag --sort v:refname | tail -n 2 | head -n 1)
      - name: Get next version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1.0
        with:
          version: ${{ steps.previous_tag.outputs.tag }}
      - name: Set development manifest
        if: steps.semvers.outputs.v_patch == steps.get_current_tag.outputs.tag
        run: |
            jq --argjson icons "{\"16\": \"icons/dev/16x16.png\",\"48\": \"icons/dev/48x48.png\",\"128\": \"icons/dev/128x128.png\"}" '.icons = $icons | .browser_action.default_icon = $icons | .name = "Liquality Wallet - Dev"' ./src/manifest.json > ./src/manifest.tmp
            mv ./src/manifest.tmp ./src/manifest.json
      - name: Set development agents
        if: steps.semvers.outputs.v_patch == steps.get_current_tag.outputs.tag
        run: |
            sed -i "s/\/swap-testnet\/agent/\/swap-testnet-dev\/agent/g; s/\/swap\/agent/\/swap-dev\/agent/g" src/store/getters.js
      - run: |
          npm ci
          npm run lint
          npm run build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/liquality-wallet-${{ steps.get_current_tag.outputs.tag }}-production.zip
          asset_name: liquality-wallet-${{ steps.get_current_tag.outputs.tag }}.zip
          asset_content_type: application/zip
      - name: Chrome Extension Publish
        uses: SebastienGllmt/chrome-addon@v3
        if: steps.semvers.outputs.v_patch == steps.get_current_tag.outputs.tag
        with:
          client-id: ${{ secrets.WEB_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.WEB_STORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.WEB_STORE_REFRESH_TOKEN }}
          zip: ./artifacts/liquality-wallet-${{ steps.get_current_tag.outputs.tag }}-production.zip
          extension: bkhfdnhibdhkbfihmljakbgnldoikgbm
          publishTarget: trustedTesters
